name: GrandSeas
version: '0.1.5-BETA'
main: me.rspaae.grandseas.GrandSeas
api-version: '1.21'
commands:
  is:
    description: Main island command
    aliases: [island, ai]
  isadmin:
    description: Admin island command
    aliases: [acid]
    permission: grandseas.admin
    permission-message: §cYou do not have permission to use this command!

permissions:
  grandseas.admin:
    description: Allows use of admin commands
    default: op
